abbr -a docker-stop-all "docker stop (docker ps -q)"
abbr -a docker-rem-all "docker rm (docker ps -aq)"
abbr -a docker-rmi-all "docker rmi (docker images -q)"
abbr -a docker-clear-cache "docker builder prune"
abbr -a docker-clear-image "docker image prune -a"
abbr -a docker-clear-container "docker container prune"
abbr -a docker-clear-volume "docker volume prune"
abbr -a docker-clear-all "docker system prune -a --volumes"
abbr -a docker-clear-network "docker network prune"
