-- return {
--   default_branch_fg = '#abb2bf',
--   default_branch_bg = nil,
--   default_fg_color = '#1A1A1A',
--   default_y_bg = nil,
--   default_bar_bg = nil,
--   default_y_fg = '#a9a9a9',
--   default_normal = '#64BAFF',
--   default_insert = '#FF7081',
--   default_visual = '#B990F7',
--   default_replace = '#ffa066',
--   default_command = '#75bf63',
--   default_location_fg = '#FFFFFF',
--   default_location_bg = nil,
-- }

return {
  a_fg = '#ECEFF4',
  a_bg = '#89b4fa',
  b_fg = '#f38ba8',
  b_bg = '#2d2d2d',
  c_fg = '#D8DEE9',
  c_bg = '#101010',
  y_fg = '#b0c4de',
  y_bg = '#101010',
  z_fg = '#ECEFF4',
  z_bg = '#3B4252',
  insert_bg = '#89b4fa',
  visual_bg = '#f38ba8',
  replace_bg = '#fab387',
  command_bg = '#f9e2af',
}
