version = 3

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '╭─'
    foreground = '#808080'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    foreground = '#ffffff'
    background = '#808080'
    type = 'os'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<parentBackground></>  '
    foreground = '#FFFB38'
    background = '#ef5350'
    type = 'root'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      root_icon = ''

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#FFFFFF'
    powerline_symbol = ''
    background = '#202020'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    leading_diamond = ' '
    trailing_diamond = ''
    template = '<#FFFFFF>{{ url .UpstreamIcon .UpstreamURL }}</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  <#22d3ee> ?{{.Working.Untracked}}</> ~{{ .Working.Modified }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}<#34d399>  {{ .StashCount }}</>{{ end }}'
    foreground = '#FFFFFF'
    background = '#111111'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFFFFF{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FB{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      branch_max_length = 25
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true
      truncate_symbol = '…'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#E4F34A'
    background = '#181818'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#42E66C'
    background = '#181818'
    type = 'node'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#E64747'
    background = '#181818'
    type = 'ruby'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#E64747'
    background = '#181818'
    type = 'java'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#A872C9'
    background = '#181818'
    type = 'php'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = ' 󰛦 {{ .Major }}.{{ .Minor }} '
    foreground = '#007ACC'
    background = '#181818'
    type = 'typescript'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#FFFFFF'
    background = '#181818'
    type = 'rust'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = '  {{ .Major }}.{{ .Minor }} '
    foreground = '#00b4AB'
    background = '#181818'
    type = 'dart'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = '#606060'
    type = 'status'
    foreground_templates = ['{{ if gt .Code 0 }}#E38073{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = '#a0a0a0'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '❯ '
    foreground = '#FFFFFF'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#E38073{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
